# Qorvo Security files
base_files = ["gpEncryption", "gpHal_SEC", "gpECC", "uECC"]

# Silex crypto soc files
silex_crypto_soc_files = [
    "sx_",
    "ba4",
    "silexCryptoSoc",
    "cryptodma",
    "crypto_nonrom",
    "cryptosoc_patch",
    "padding",
    "memcmp",
]

# mbedtls files - list inspired on External/mbedtls listing - should capture _alt as well
mbed_tls_files = [
    "aes",
    "aesni",
    "arc4",
    "asn1parse",
    "asn1write",
    "base64",
    "bignum",
    "blowfish",
    "camellia",
    "ccm",
    "certs",
    "cipher",
    "cipher_wrap",
    "cmac",
    "ctr_drbg",
    "debug",
    "des.",
    "dhm",
    "ecdh",
    "ecdsa",
    "ecjpake",
    "ecp",
    "ecp_curves",
    "entropy",
    "entropy_poll",
    "error",
    "gcm",
    "hkdf",
    "hmac_drbg",
    "md",
    "md5",
    "md_wrap",
    "oid",
    "pem",
    "pk",
    "pk_wrap",
    "pkcs12",
    "pkcs5",
    "pkparse",
    "pkwrite",
    "platform",
    "platform_util",
    "ripemd160",
    "sha1",
    "sha256",
    "sha512",
    "ssl_cache",
    "ssl_ciphersuites",
    "ssl_cli",
    "ssl_cookie",
    "ssl_srv",
    "ssl_ticket",
    "ssl_tls",
    "ssl_msg",
    "threading",
    "timing",
    "trng",
    "version",
    "version_features",
    "x509",
    "x509_create",
    "x509_crl",
    "x509_csr",
    "x509write_crt",
    "x509write_csr",
    "xtea",
]

default = {"Components/Qorvo/BaseUtils": {"gpEncryption": [],
                                          "silexCryptoSoc": [], },
           "Components/Qorvo/HAL_RF": {"gphal": ["gpHal_SEC"], },
           "Components/Qorvo/BleController": {"gpECC": [], },
           "cryptosoc": {},
           "cordio-r19-02": {"ble-host": ["sec"], },
           "uECC": {},
           },
